#!/bin/sh

# Modify this script to pass the necessary parameters to 
# the configure of the captive package you're configuring
prefix="/usr/local"
exec_prefix="${prefix}"
CPPFLAGS=""
LDFLAGS="-arch arm64 "
CFLAGS="-arch arm64 -g -O2"
CXXFLAGS="-arch arm64 "
HOST_TYPE=Mac
HOST_OS=aarch64-apple-darwin23.6.0

if [ "" = "1" ]; then
  CROSS="--host ${HOST_OS}"
else
  CROSS=
fi

CFLAGS="-arch arm64 -g -O2"
case $HOST_OS in
  *mingw*|*cygwin*)
  # on windows we need to disable force inline
  CFLAGS="-DFORCEINLINE= ${CFLAGS}"
  ;;
  *)
  ;;
esac

CC="gcc" \
CFLAGS="-I${prefix}/include ${CFLAGS}" \
LD="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" \
LDFLAGS="-L${exec_prefix}/lib -arch arm64 " \
CPP="gcc -E" \
CPPFLAGS="" \
CXX="g++ -std=gnu++11" \
CXXFLAGS="-arch arm64 " \
NM="/usr/bin/nm -B" \
AS="as" \
ASFLAGS="" \
STRIP="strip" \
RANLIB="ranlib" \
AR="ar" \
DLLTOOL="false" \
PATH="$PATH:/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu${exec_prefix}/bin@" sh /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libmp3lame/csrc/configure \
  ${CROSS} \
  --with-pic \
  --disable-shared \
  --prefix="${prefix}" || \
  (echo "Could not configure library: \"/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libmp3lame\"; you may want to try disabling it or installing your own version" && exit 1)
