#!/bin/sh

# Modify this script to pass the necessary parameters to 
# the configure of the captive package you're configuring
prefix="/usr/local"
exec_prefix="${prefix}"
CPPFLAGS=""
LDFLAGS=""
CFLAGS="-g -O2"
CXXFLAGS=""
HOST_TYPE=Mac
HOST_OS=arm-apple-darwin23.6.0

if [ "" = "1" ]; then
  CROSS="--host ${HOST_OS}"
else
  CROSS=
fi

DISABLE_ASM=
VS_CFLAGS="-g -O2"
case $HOST_OS in
  *darwin*)
  DISABLE_ASM="--disable-asm"
  VS_CFLAGS="-Wno-error=unused-command-line-argument-hard-error-in-future -g -O2"
  ;;
  *)
  ;;
esac

CC="gcc" \
CFLAGS="-I${prefix}/include ${VS_CFLAGS}" \
LD="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" \
LDFLAGS="-L${exec_prefix}/lib " \
CPP="gcc -E" \
CPPFLAGS="" \
CXX="g++" \
CXXFLAGS="" \
NM="/usr/bin/nm -B" \
AS="as" \
ASFLAGS="" \
STRIP="strip" \
RANLIB="ranlib" \
AR="ar" \
DLLTOOL="false" \
PATH="$PATH:/Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu${exec_prefix}/bin@" sh /Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libtheora/csrc/configure \
  --disable-dependency-tracking \
  --with-pic \
  --disable-shared \
  ${CROSS} \
  --prefix="${prefix}" \
  --disable-examples ${DISABLE_ASM} || \
  (echo "Could not configure library: \"/Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libtheora\"; you may want to try disabling it or installing your own version" && exit 1)
