#!/bin/sh

# Modify this script to pass the necessary parameters to 
# the configure of the captive package you're configuring
prefix="/usr/local"
exec_prefix="${prefix}"
CPPFLAGS=""
LDFLAGS="-arch arm64 "
CFLAGS="-arch arm64 -g -O2"
CXXFLAGS="-arch arm64 "
HOST_TYPE=Mac
HOST_OS=aarch64-apple-darwin24.4.0

if [ "" = "1" ]; then
  CROSS="--host ${HOST_OS}"
else
  CROSS=
fi

DISABLE_ASM=
VS_CFLAGS="-arch arm64 -g -O2"
case $HOST_OS in
  *darwin*)
  DISABLE_ASM="--disable-asm"
  VS_CFLAGS="-Wno-error=unused-command-line-argument-hard-error-in-future -arch arm64 -g -O2"
  ;;
  *)
  ;;
esac

CC="gcc" \
CFLAGS="-I${prefix}/include ${VS_CFLAGS}" \
LD="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" \
LDFLAGS="-L${exec_prefix}/lib -arch arm64 " \
CPP="gcc -E" \
CPPFLAGS="" \
CXX="g++" \
CXXFLAGS="-arch arm64 " \
NM="/usr/bin/nm -B" \
AS="as" \
ASFLAGS="" \
STRIP="strip" \
RANLIB="ranlib" \
AR="ar" \
DLLTOOL="false" \
PATH="$PATH:/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu${exec_prefix}/bin@" sh /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libtheora/csrc/configure \
  --disable-dependency-tracking \
  --with-pic \
  --disable-shared \
  ${CROSS} \
  --prefix="${prefix}" \
  --disable-examples ${DISABLE_ASM} || \
  (echo "Could not configure library: \"/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libtheora\"; you may want to try disabling it or installing your own version" && exit 1)
