#!/bin/sh

# Modify this script to pass the necessary parameters to 
# the configure of the captive package you're configuring
prefix="/usr/local"
exec_prefix="${prefix}"
CPPFLAGS=""
LDFLAGS=""
CFLAGS="-g -O2"
CXXFLAGS=""
HOST_TYPE=Mac
HOST_OS=arm-apple-darwin23.6.0

if [ "" = "1" ]; then
  CROSS="--host ${HOST_OS}"
else
  CROSS=
fi

CC="gcc" \
CFLAGS="-I${prefix}/include -g -O2" \
LD="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" \
LDFLAGS="-L${exec_prefix}/lib " \
CPP="gcc -E" \
CPPFLAGS="" \
CXX="g++" \
CXXFLAGS="" \
NM="/usr/bin/nm -B" \
AS="as" \
ASFLAGS="" \
STRIP="strip" \
RANLIB="ranlib" \
AR="ar" \
DLLTOOL="false" \
PATH="$PATH:/Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu${exec_prefix}/bin@" sh /Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libvorbis/csrc/configure \
  LIBS="-logg" \
  ${CROSS} \
  --disable-dependency-tracking \
  --with-pic \
  --disable-shared \
  --prefix="${prefix}" || \
  (echo "Could not configure library: \"/Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libvorbis\"; you may want to try disabling it or installing your own version" && exit 1)
