#!/bin/sh

# Modify this script to pass the necessary parameters to 
# the configure of the captive package you're configuring
prefix="/usr/local"
exec_prefix="${prefix}"
LIBRARY=libopencore-amr
LIBRARY_OPTIONS=
HOST_TYPE=Mac
HOST_OS=aarch64-apple-darwin24.4.0
BUILD_STR=aarch64-apple-darwin24.4.0

if [ "" = "1" ]; then
  CROSS="--build ${BUILD_STR} --host ${HOST_OS}"
else
  CROSS=
fi

# LIBRARY doesn't support VPATH builds, so we fake it
echo "Copying /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libopencore-amr/csrc to /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libopencore-amr/csrc"
# create the directory
mkdir -p /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libopencore-amr/csrc
# copy over all the source
cp -r /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libopencore-amr/csrc/* /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libopencore-amr/csrc/
# and make everything user writeable so distcheck will pass
chmod -R u+w /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libopencore-amr/csrc/*

if [ ! -f /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libopencore-amr/csrc/configure ]; then
    # sigh... looks like they don't check in with configure. Rebuild it.
    (cd /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libopencore-amr/csrc/ && autoreconf --install --force)
fi

LIBRARY_OPTIONS="--disable-dependency-tracking \
   --with-pic \
   --disable-shared \
   ${CROSS} \
  --prefix="${prefix}" $LIBRARY_OPTIONS"

echo "Configuring ${LIBRARY} with these options: $LIBRARY_OPTIONS"
CC="gcc" \
CXX="g++" \
CFLAGS="-I${prefix}/include -arch arm64 -g -O2" \
LD="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" \
LDFLAGS="-L${exec_prefix}/lib -arch arm64 " \
CPP="@CPP@" \
CPPFLAGS="" \
CXX="g++" \
CXXFLAGS="-arch arm64 " \
NM="/usr/bin/nm -B" \
AS="as" \
ASFLAGS="" \
STRIP="strip" \
RANLIB="ranlib" \
AR="ar" \
DLLTOOL="false" \
PATH="$PATH:/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu${exec_prefix}/bin@" \
   sh /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libopencore-amr/csrc/configure $LIBRARY_OPTIONS || \
  (echo "Could not configure library: \"/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libopencore-amr\"; you may want to try disabling it or installing your own version" && exit 1)
