#!/bin/sh

# Modify this script to pass the necessary parameters to 
# the configure of the captive package you're configuring
prefix="/usr/local"
exec_prefix="${prefix}"
X264_OPTIONS=
LDFLAGS=""
CFLAGS="-g -O2"
NASM="/opt/homebrew/bin/nasm"
HOST_TYPE=Mac
HOST_OS=arm-apple-darwin23.6.0
VS_DEBUG=

# For mac we want to force a cross compilation, but have it use
# the default tooling (no prefix for nasm)
if [ "" = "1" -o "${HOST_TYPE}" = "Mac" ]; then
  X264_OPTIONS="${X264_OPTIONS} --host=${HOST_OS} --cross-prefix="
fi

# Tell X264 about the captive libraries already built and fake
# installed

X264_OPTIONS="$X264_OPTIONS --enable-static"
X264_OPTIONS="$X264_OPTIONS --enable-pic"

#if test "${HOST_TYPE}" = "Mac" ; then
#  echo "Forcing debug build on Mac OS X due to text relocation in x264_cabac_encode_decision_asm; remove when x264 fixes that"
#  VS_DEBUG=1 
#fi
if test ! "x$VS_DEBUG" = "x"; then
  echo "Creating debug version of libx264: $VS_DEBUG"
  X264_OPTIONS="$X264_OPTIONS --disable-asm"
  X264_OPTIONS="$X264_OPTIONS --enable-debug"
else
  echo "Creating release version of libx264: $VS_DEBUG"
fi

if test "x$NASM" = "x"; then
# no assembly for us :(
  X264_OPTIONS="$X264_OPTIONS --disable-asm"
fi

# X264, despite claiming it, does not support in-tree builds,
# and so we copy the entire source
# directory to the build directory, and then build in place.
# copy over all the source
if [ ! -f "/Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libx264/csrc/configure" ]; then
  echo "Copying /Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libx264/csrc to /Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libx264/csrc"
  # create the directory
  mkdir -p "/Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libx264/csrc"
  # copy over all the source
  cp -r "/Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libx264/csrc/"* "/Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libx264/csrc/"
  # and make everything user writeable so distcheck will pass
  chmod -R u+w "/Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libx264/csrc/"*
fi

echo "Configuring X264 with these options: $X264_OPTIONS"
CC="gcc" \
CFLAGS="-I${prefix}/include -I/Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libx264/csrc/ -g -O2" \
LD="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" \
LDFLAGS="-L${exec_prefix}/lib " \
CPP="gcc -E" \
CPPFLAGS="" \
CXX="g++" \
CXXFLAGS="" \
NM="/usr/bin/nm -B" \
AS="as" \
ASFLAGS="" \
STRIP="strip" \
RANLIB="ranlib" \
AR="ar" \
AS="/opt/homebrew/bin/nasm" \
DLLTOOL="false" \
PATH="$PATH:/Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu${exec_prefix}/bin@" bash /Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libx264/csrc/configure \
  --extra-cflags="-I'${prefix}/include' -I'/Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libx264/csrc/' $CFLAGS" \
  --extra-ldflags="$LDFLAGS -L'${exec_prefix}/lib'" \
  --prefix="${prefix}" $X264_OPTIONS || \
  (echo "Could not configure library: \"/Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libx264\"; you may want to try disabling it or installing your own version" && exit 1)
