#!/bin/sh

# Modify this script to pass the necessary parameters to 
# the configure of the captive package you're configuring
prefix="/usr/local"
exec_prefix="${prefix}"
X264_OPTIONS=
LDFLAGS="-arch arm64 "
CFLAGS="-arch arm64 -g -O2"
NASM="/opt/homebrew/bin/nasm"
HOST_TYPE=Mac
HOST_OS=aarch64-apple-darwin24.4.0
VS_DEBUG=

# For mac we want to force a cross compilation, but have it use
# the default tooling (no prefix for nasm)
if [ "" = "1" -o "${HOST_TYPE}" = "Mac" ]; then
  X264_OPTIONS="${X264_OPTIONS} --host=${HOST_OS} --cross-prefix="
fi

# Tell X264 about the captive libraries already built and fake
# installed

X264_OPTIONS="$X264_OPTIONS --enable-static"
X264_OPTIONS="$X264_OPTIONS --enable-pic"

#if test "${HOST_TYPE}" = "Mac" ; then
#  echo "Forcing debug build on Mac OS X due to text relocation in x264_cabac_encode_decision_asm; remove when x264 fixes that"
#  VS_DEBUG=1 
#fi
if test ! "x$VS_DEBUG" = "x"; then
  echo "Creating debug version of libx264: $VS_DEBUG"
  X264_OPTIONS="$X264_OPTIONS --enable-debug"
  if [ "$HOST_TYPE" != "Mac" ]; then
    echo "No Mac, disabling asm"
    X264_OPTIONS="$X264_OPTIONS --disable-asm"
  fi
else
  echo "Creating release version of libx264: $VS_DEBUG"
fi

if test "x$NASM" = "x"; then
  # no assembly for us :(
  if [ "$HOST_TYPE" != "Mac" ]; then
    echo "No Mac, disabling asm"
    X264_OPTIONS="$X264_OPTIONS --disable-asm"
  fi
fi


# X264, despite claiming it, does not support in-tree builds,
# and so we copy the entire source
# directory to the build directory, and then build in place.
# copy over all the source
if [ ! -f "/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libx264/csrc/configure" ]; then
  echo "Copying /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libx264/csrc to /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libx264/csrc"
  # create the directory
  mkdir -p "/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libx264/csrc"
  # copy over all the source
  cp -r "/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libx264/csrc/"* "/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libx264/csrc/"
  # and make everything user writeable so distcheck will pass
  chmod -R u+w "/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libx264/csrc/"*
fi

echo "Configuring X264 with these options: $X264_OPTIONS"
CC="gcc" \
CFLAGS="-I${prefix}/include -I/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libx264/csrc/ -I/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libx264/../ffmpeg/csrc/ -arch arm64 -g -O2" \
LD="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" \
LDFLAGS="-L${exec_prefix}/lib -arch arm64 " \
CPP="@CPP@" \
CPPFLAGS="" \
CXX="g++" \
CXXFLAGS="-arch arm64 " \
NM="/usr/bin/nm -B" \
AS="as" \
ASFLAGS="" \
STRIP="strip" \
RANLIB="ranlib" \
AR="ar" \
AS="clang -c" \
DLLTOOL="false" \
PATH="$PATH:/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu${exec_prefix}/bin@" bash /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libx264/csrc/configure \
  --extra-cflags="-I'${prefix}/include' -I'/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libx264/csrc/' $CFLAGS" \
  --extra-ldflags="$LDFLAGS -L'${exec_prefix}/lib'" \
  --prefix="${prefix}" $X264_OPTIONS || \
  (echo "Could not configure library: \"/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libx264\"; you may want to try disabling it or installing your own version" && exit 1)
  
