#!/bin/sh

# Modify this script to pass the necessary parameters to 
# the configure of the captive package you're configuring
prefix="/usr/local"
exec_prefix="${prefix}"
HOST_TYPE=Mac
HOST_OS=aarch64-apple-darwin24.4.0
HOST_CPU=aarch64
HOST_VENDOR=apple
HOST_OS_C=darwin24.4.0

VS_DEBUG=

CAPTIVE_ENABLE_FFMPEG_GPL=yes

FFMPEG_OPTIONS=
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --extra-version=humble-0.3"

# Tell FFMPEG about the captive libraries already built and fake
# installed
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --extra-cflags=-I${prefix}/include"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --extra-ldflags=-L${exec_prefix}/lib"
# Set up a place where pkg-config looks for installed packages
export PKG_CONFIG_PATH="${exec_prefix}/lib/pkgconfig"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --pkg-config-flags=--static"

FFMPEG_OPTIONS="$FFMPEG_OPTIONS --disable-shared"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-pic"
#FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-runtime-cpudetect"

# Disable GUI/X11 stuff for headless and portable builds
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --disable-xlib"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --disable-libxcb"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --disable-libxcb-shm"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --disable-libxcb-xfixes"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --disable-indev=xcbgrab"
#FFMPEG_OPTIONS="$FFMPEG_OPTIONS --disable-sdl2"
#FFMPEG_OPTIONS="$FFMPEG_OPTIONS --disable-ffplay"


if test "x$CAPTIVE_ENABLE_FFMPEG_GPL" = "xyes"; then
  FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-gpl --enable-nonfree"
  # x264 can only be used in GPL mode
  FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-libx264"
fi
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-version3"

case $HOST_OS in
  *darwin*)
    # GNU Configure sometimes adds darwin version numbers; this strips them
    HOST_OS_C=darwin
    # Sigh; but on Xcode 4.2 there is a compiler bug with register allocation.  
    # Rather than expensively detect the compiler version, I'm going to hard-code
    # darwin builds for now to debug (no assembly) and wait for a compiler or ffmpeg
    # fix
#    VS_DEBUG=1
  FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-pthreads"
  ;;
esac
if [ "" = "1" ]; then
  FFMPEG_OPTIONS="${FFMPEG_OPTIONS} --enable-cross-compile --cross-prefix= --arch=${HOST_CPU} --target-os=${HOST_OS_C}"
  
  # Ensure pkg-config is set correctly to find our custom-built native libs
  export PKG_CONFIG_PATH="${exec_prefix}/lib/pkgconfig"
  FFMPEG_OPTIONS="${FFMPEG_OPTIONS} --pkg-config=pkg-config"
  
  echo "PKG_CONFIG_PATH set to: ${PKG_CONFIG_PATH}"
  echo "FFMPEG will use pkg-config to locate libvpx and other libraries"
fi


if test ! "x$VS_DEBUG" = "x"; then
  FFMPEG_OPTIONS="$FFMPEG_OPTIONS --disable-stripping"
  FFMPEG_OPTIONS="$FFMPEG_OPTIONS --disable-asm"
  FFMPEG_OPTIONS="$FFMPEG_OPTIONS --disable-optimizations"
  FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-debug=3"
fi
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-libmp3lame"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-libvorbis"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-libtheora"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-libspeex"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-libvo-aacenc"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-libopencore-amrnb --enable-libopencore-amrwb"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-librtmp"
case $HOST_OS in
  *mingw*|*cygwin*)
   # ffmpeg configure doesn't handle pkg-config files correctly when
   # static linking, so we fix librtmp here.
   FFMPEG_OPTIONS="$FFMPEG_OPTIONS --extra-libs=-lws2_32"
   FFMPEG_OPTIONS="$FFMPEG_OPTIONS --extra-libs=-lwinmm"
   FFMPEG_OPTIONS="$FFMPEG_OPTIONS --extra-libs=-lgdi32"
  ;;
esac
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-openssl"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-zlib"
FFMPEG_OPTIONS="$FFMPEG_OPTIONS --enable-libvpx"

# LIBRARY doesn't support VPATH builds, so we fake it
echo "Copying /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/ffmpeg/csrc to /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/ffmpeg/csrc"
# create the directory
mkdir -p /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/ffmpeg/csrc
# copy over all the source
cp -r /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/ffmpeg/csrc/* /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/ffmpeg/csrc/
# and make everything user writeable so distcheck will pass
chmod -R u+w /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/ffmpeg/csrc/*

# apply all the patches
echo "Applying patches to /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/ffmpeg/csrc/src"
(cd /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/ffmpeg/csrc && for f in /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/ffmpeg/patches/*; do echo "patch -p1 <$f"; patch -p1 <$f; done)
echo "------ DEBUG PKG_CONFIG ------"
which pkg-config
pkg-config --modversion vpx || echo "Failed to query libvpx via pkg-config"
pkg-config --cflags vpx || echo "Failed to get cflags"
pkg-config --libs vpx || echo "Failed to get libs"
echo "------------------------------"

echo "Configuring FFMPEG with these options: $FFMPEG_OPTIONS"
cd /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/ffmpeg/csrc
CC="gcc" \
LD="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" \
CPP="@CPP@" \
CPPFLAGS="" \
CXX="g++" \
CXXFLAGS="-arch arm64 " \
NM="/usr/bin/nm -B" \
AS="as" \
ASFLAGS="" \
STRIP="strip" \
RANLIB="ranlib" \
AR="ar" \
DLLTOOL="false" \
PATH="$PATH:/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu${exec_prefix}/bin@" sh /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/ffmpeg/csrc/configure \
  --prefix="${prefix}" $FFMPEG_OPTIONS || \
  (echo "Could not configure library: \"/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/ffmpeg\"; you may want to try disabling it or installing your own version" && exit 1)
# Attempt to stop unnecessary re-configs by touching this
MAKEFILE="/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/ffmpeg/csrc/Makefile"
if [ -f "${MAKEFILE}" ]; then
  echo "Updating ${MAKEFILE} to stop unnecessary builds"
  touch "${MAKEFILE}"
fi
