#!/bin/sh

# Modify this script to pass the necessary parameters to 
# the configure of the captive package you're configuring
prefix="/usr/local"
exec_prefix="${prefix}"
HOST_OS=arm-apple-darwin23.6.0

if [ "" = "1" ]; then
  CROSS="--host ${HOST_OS}"
else
  CROSS=
fi

CFLAGS="-I${prefix}/include -O0 -g -O2" 

case ${HOST_OS} in
  *darwin*)
  CFLAGS="-DHAVE_APPLE_OPENGL_FRAMEWORK ${CFLAGS}"
  ;;
esac

CC="gcc" \
CFLAGS="${CFLAGS}" \
LD="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" \
LDFLAGS="-L${exec_prefix}/lib " \
CPP="gcc -E" \
CPPFLAGS="" \
CXX="g++" \
CXXFLAGS="" \
NM="/usr/bin/nm -B" \
AS="as" \
ASFLAGS="" \
STRIP="strip" \
RANLIB="ranlib" \
AR="ar" \
DLLTOOL="false" \
PATH="$PATH:/Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu${exec_prefix}/bin@" sh /Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libtiff/csrc/configure \
  ${CROSS} \
  --with-zlib-include-dir="${prefix}/include" \
  --with-zlib-lib-dir="${exec_prefix}/lib" \
  --with-pic \
  --disable-shared \
  --disable-dependency-tracking \
  --prefix="${prefix}" || \
  (echo "Could not configure library: \"/Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libtiff\"; you may want to try disabling it or installing your own version" && exit 1)
