#!/bin/sh

# Modify this script to pass the necessary parameters to 
# the configure of the captive package you're configuring
prefix="/usr/local"
exec_prefix="${prefix}"
HOST_OS=aarch64-apple-darwin23.6.0

if [ "" = "1" ]; then
  CROSS="--host ${HOST_OS}"
  # needed for mingw32 cross-compile to work
  case $HOST_OS in
    *mingw*|*cygwin*)
    export as_cv_unaligned_access=yes
    ;;
  esac
else
  CROSS=
fi

CC="gcc" \
CFLAGS="-I${prefix}/include -O0 -arch arm64 -g -O2" \
LD="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" \
LDFLAGS="-L${exec_prefix}/lib -arch arm64 " \
CPP="@CPP@" \
CPPFLAGS="" \
CXX="g++ -std=gnu++11" \
CXXFLAGS="-arch arm64 " \
NM="/usr/bin/nm -B" \
AS="as" \
ASFLAGS="" \
STRIP="strip" \
RANLIB="ranlib" \
AR="ar" \
DLLTOOL="false" \
PATH="$PATH:/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu${exec_prefix}/bin@" sh /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/liboil/csrc/configure \
  ${CROSS} \
  --disable-dependency-tracking \
  --disable-glib \
  --with-pic \
  --disable-shared \
  --prefix="${prefix}" || \
  (echo "Could not configure library: \"/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/liboil\"; you may want to try disabling it or installing your own version" && exit 1)
