#!/bin/sh

# Modify this script to pass the necessary parameters to 
# the configure of the captive package you're configuring
prefix="/usr/local"
exec_prefix="${prefix}"
HOST_OS=arm-apple-darwin23.6.0

if [ "" = "1" ]; then
  CROSS="--host ${HOST_OS}"
  # needed for mingw32 cross-compile to work
  case $HOST_OS in
    *mingw*|*cygwin*)
    export as_cv_unaligned_access=yes
    ;;
  esac
else
  CROSS=
fi

CC="gcc" \
CFLAGS="-I${prefix}/include -O0 -g -O2" \
LD="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" \
LDFLAGS="-L${exec_prefix}/lib " \
CPP="gcc -E" \
CPPFLAGS="" \
CXX="g++" \
CXXFLAGS="" \
NM="/usr/bin/nm -B" \
AS="as" \
ASFLAGS="" \
STRIP="strip" \
RANLIB="ranlib" \
AR="ar" \
DLLTOOL="false" \
PATH="$PATH:/Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu${exec_prefix}/bin@" sh /Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/liboil/csrc/configure \
  ${CROSS} \
  --disable-dependency-tracking \
  --disable-glib \
  --with-pic \
  --disable-shared \
  --prefix="${prefix}" || \
  (echo "Could not configure library: \"/Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/liboil\"; you may want to try disabling it or installing your own version" && exit 1)
