#!/bin/sh

# Modify this script to pass the necessary parameters to 
# the configure of the captive package you're configuring
prefix="/usr/local"
exec_prefix="${prefix}"
LIBRARY=libvo-aacenc
LIBRARY_OPTIONS=
HOST_TYPE=Mac
HOST_OS=arm-apple-darwin23.6.0

if [ "" = "1" ]; then
  CROSS="--host ${HOST_OS}"
else
  CROSS=
fi

# LIBRARY doesn't support VPATH builds, so we fake it
echo "Copying /Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libvo-aacenc/csrc to /Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libvo-aacenc/csrc"
# create the directory
mkdir -p /Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libvo-aacenc/csrc
# copy over all the source
cp -r /Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libvo-aacenc/csrc/* /Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libvo-aacenc/csrc/
# and make everything user writeable so distcheck will pass
chmod -R u+w /Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libvo-aacenc/csrc/*

if [ ! -f /Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libvo-aacenc/csrc/configure ]; then
    # sigh... looks like they don't check in with configure. Rebuild it.
    (cd /Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libvo-aacenc/csrc/ && autoreconf --install --force)
fi

echo "Configuring ${LIBRARY} with these options: $LIBRARY_OPTIONS"
CC="gcc" \
CFLAGS="-I${prefix}/include -g -O2" \
LD="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" \
LDFLAGS="-L${exec_prefix}/lib " \
CPP="gcc -E" \
CPPFLAGS="" \
CXX="g++" \
CXXFLAGS="" \
NM="/usr/bin/nm -B" \
AS="as" \
ASFLAGS="" \
STRIP="strip" \
RANLIB="ranlib" \
AR="ar" \
DLLTOOL="false" \
PATH="$PATH:/Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu${exec_prefix}/bin@" \
   sh /Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libvo-aacenc/csrc/configure \
   --enable-silent-rules \
   --disable-dependency-tracking \
   --with-pic \
   --disable-shared \
   ${CROSS} \
  --prefix="${prefix}" $LIBRARY_OPTIONS || \
  (echo "Could not configure library: \"/Library/Java/Extensions/humble-video-master/humble-video-captive/src/main/gnu/libvo-aacenc\"; you may want to try disabling it or installing your own version" && exit 1)
