#!/bin/sh

# Modify this script to pass the necessary parameters to 
# the configure of the captive package you're configuring
prefix="/usr/local"
exec_prefix="${prefix}"
CPPFLAGS=""
LDFLAGS="-arch arm64 "
CFLAGS="-arch arm64 -g -O2"
CXXFLAGS="-arch arm64 "
HOST_TYPE=Mac
HOST_OS=aarch64-apple-darwin24.4.0

if [ "" = "1" ]; then
  CROSS="--host ${HOST_OS}"
else
  CROSS=
fi

CC="gcc" \
CFLAGS="-I${prefix}/include -arch arm64 -g -O2" \
LD="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" \
LDFLAGS="-L${exec_prefix}/lib -arch arm64 " \
CPP="@CPP@" \
CPPFLAGS="" \
CXX="g++" \
CXXFLAGS="-arch arm64 " \
NM="/usr/bin/nm -B" \
AS="as" \
ASFLAGS="" \
STRIP="strip" \
RANLIB="ranlib" \
AR="ar" \
DLLTOOL="false" \
PATH="$PATH:/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu${exec_prefix}/bin@" sh /Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libspeex/csrc/configure \
  --disable-dependency-tracking \
  --with-pic \
  --disable-shared \
  --enable-sse \
  ${CROSS} \
  --prefix="${prefix}" || \
  (echo "Could not configure library: \"/Users/markuswienkemeier/Desktop/Uni/BA_neu/humble-video/humble-video-captive/src/main/gnu/libspeex\"; you may want to try disabling it or installing your own version" && exit 1)
