/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.humble.video;

/**
 * Internal Only.
 * 
 */

public class Video {

  static {
    // Force the JNI library to load
    VideoJNI.noop();
  }

  /**
   * Method to force loading of all native methods in the library.
   */
  public static void load() {}

  /**
   * Internal Only.  Do not use.
   */
  public native static void init();


}
